ALTER TABLE admins
  ADD COLUMN IF NOT EXISTS profile_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS experience_years INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS photo_url VARCHAR(500) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS expertise VARCHAR(500) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS website_url VARCHAR(500) DEFAULT NULL;